scores:
  tgUrl: 20
  url: 5
  isABot: 40
# TODO: add
multipliers:
  firstMsg: 2
actions:
  del: 40
  kick: 80
  ban: 100
  ban2dayFactor: 50
urllists:
  exchanges:
    score: 20
    domains:
      - bittrex.com
      - cryptopia.com
wordlists:
  exchanges:
    score: 20
    words:
     - bitmex
     - bittrex
     - bitrex
     - cryptopia
  crypto-currencies:
    score: 10
    words:
     - eth
     - btc
     - bch
     - ltc
     - doge
  generic-words:
    score: 5
    words:
     - airdrop
     - giveaway
     - group
     - pump
     - coin
